# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-07-11 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_player_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.TextField()),
                ('options', models.IntegerField(default=5)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('hidden', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('datetime',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=19)),
            ],
        ),
        migrations.RemoveField(
            model_name='bid',
            name='game',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='bid_winner',
        ),
        migrations.RemoveField(
            model_name='game',
            name='minimum',
        ),
        migrations.RemoveField(
            model_name='game',
            name='next_to_bid',
        ),
        migrations.RemoveField(
            model_name='game',
            name='partner1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='partner2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='room',
        ),
        migrations.RemoveField(
            model_name='hand',
            name='game',
        ),
        migrations.RemoveField(
            model_name='hand',
            name='hand_winner',
        ),
        migrations.RemoveField(
            model_name='handentry',
            name='hand',
        ),
        migrations.RemoveField(
            model_name='handentry',
            name='player',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='player',
            name='room',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Hand',
        ),
        migrations.DeleteModel(
            name='HandEntry',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.AddField(
            model_name='answer',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='chat.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='for_q',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='chat.Question'),
        ),
    ]
