# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-07-11 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20200711_0756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('datetime',)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('datetime',)},
        ),
        migrations.AddField(
            model_name='answer',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
